server:
  port: ${SUBSCRIPTION_SERVICE_PORT:0}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ${SUBSCRIPTION_SERVICE_NAME:subscription-service}

  data:
    mongodb:
      uri: ${SUBSCRIPTION_SERVICE_MONGODB_URI:uri}
      database: ${SUBSCRIPTION_SERVICE_MONGODB_DATABASE:subscription-service-db}
      auto-index-creation: true

  kafka:
    bootstrap-servers: ${CLOUD_KAFKA_BROKER_URL}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required
            username="${CLOUD_KAFKA_USERNAME}" password="${CLOUD_KAFKA_PASSWORD}";

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable:
          idempotence: false
        spring:
          json:
            add:
              type:
                headers: false

kafka:
  topic:
    in: ${CLOUD_KAFKA_USERNAME}-${SUBSCRIPTION_SERVICE_TOPIC:subscription-topic}