server:
  port: ${SUBSCRIPTION_SERVICE_PORT:0}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ${SUBSCRIPTION_SERVICE_NAME:subscription-service}

  threads:
    virtual:
      enabled: true

  data:
    mongodb:
      uri: ${SUBSCRIPTION_SERVICE_MONGODB_URI:uri}
      database: ${SUBSCRIPTION_SERVICE_MONGODB_DATABASE:subscription-service-db}
      auto-index-creation: true

kafka:
  topic:
    out: ${CLOUD_KAFKA_USERNAME}-${SUBSCRIPTION_SERVICE_TOPIC_OUT:rss-topic}
  server:
    bootstrapServer: ${CLOUD_KAFKA_BROKER_URL}
    propertySecurityProtocol: SASL_SSL
    propertySaslMechanism: SCRAM-SHA-256
    propertySaslJaasConfig: org.apache.kafka.common.security.scram.ScramLoginModule required
      username="${CLOUD_KAFKA_USERNAME}" password="${CLOUD_KAFKA_PASSWORD}";
  producer:
    keySerializer: org.apache.kafka.common.serialization.StringSerializer
    valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
    propertyEnableIdempotence: false
    propertySpringJsonAddTypeHeaders: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health