###
GET http://localhost:8080/v1/subscriptions

###
POST http://localhost:8080/v1/subscriptions
Content-Type: application/json

{
  "chatId": -1001600823930,
  "imageId": "6619963275ced443a63c3456",
  "templateId": "662c96f3a4d53c774c815f51",
  "customizationId": "662c96f3a4d53c774c815f54",
  "rss": "https://habr.com/ru/rss/articles/?fl=ru",
  "filterIds": [
    "66218df402ace91dcffcddae",
    "662415cffc13084689b00a35"
  ],
  "isActive": true
}

###
PATCH http://localhost:8080/v1/subscriptions/66218f8b1512f67839bc5234