server:
  port: ${SCHEDULER_SERVICE_PORT:0}
  error:
    include-stacktrace: always
    include-message: always

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ${SCHEDULER_SERVICE_NAME:scheduler_service}

  boot:
    admin:
      client:
        enabled: ${ADMIN_SERVICE_ENABLE_MONITORING:false}
        url: ${ADMIN_SERVICE_URL:http://localhost:8999}

  threads:
    virtual:
      enabled: true

custom:
  rabbitmq:
    username: ${SCHEDULER_SERVICE_RABBITMQ_USERNAME:****}
    password: ${SCHEDULER_SERVICE_RABBITMQ_PASSWORD:****}
    port: ${SCHEDULER_SERVICE_RABBITMQ_PORT:5672}
    host: ${SCHEDULER_SERVICE_RABBITMQ_HOST:localhost}
    virtualhost: ${SCHEDULER_SERVICE_RABBITMQ_VIRTUAL_HOST:****}
    queue:
      subscription: ${SCHEDULER_SERVICE_RABBITMQ_QUEUE_SUBSCRIPTION:subscription_service_queue}
    exchange:
      subscription: ${SCHEDULER_SERVICE_RABBITMQ_EXCHANGE_SUBSCRIPTION:subscription_service_exchange}
    routing:
      key:
        subscription: ${SCHEDULER_SERVICE_RABBITMQ_R_KEY_SUBSCRIPTION:subscription_service_routing_key}

scheduled:
  processing:
    cron: ${SCHEDULER_SERVICE_SCHEDULER_PROCESSING_CRONE:0 */1 * * * *}

management:
  endpoints:
    web:
      exposure:
        include: '*'